spring:
  application:
    name: jifeng-mall-brand-api

  cloud:
    nacos:
      discovery:
        port: 10010
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        username: nacos
        password: 123456
        group: jifeng-mall
        namespace: jifeng-mall

  config:
    import: nacos:jifeng-mall-common.yaml

server:
  port: 10010

# 启用openfeign服务降级（删除品牌/分类前要调 good-api 校验商品引用）
feign:
  sentinel:
    enabled: on
