<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.situ</groupId>
        <artifactId>jifeng-mall-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>jifeng-mall-api</artifactId>
    <name>jifeng-mall-api</name>
    <description>所有微服务的父项目</description>
    <packaging>pom</packaging>

    <modules>
        <module>jifeng-mall-brand-api</module>
        <module>jifeng-mall-good-api</module>
        <module>jifeng-mall-category-api</module>
        <module>jifeng-mall-member-api</module>
        <module>jifeng-mall-member-address-api</module>
        <module>jifeng-mall-region-api</module>
        <module>jifeng-mall-cart-api</module>
        <module>jifeng-mall-order-api</module>
        <module>jifeng-mall-user-api</module>
        <module>jifeng-mall-seckill-api</module>
        <module>jifeng-mall-rbac-api</module>
        <module>jifeng-mall-upload-api</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
            <scope>provided</scope>
        </dependency>

        <!--nacos服务治理-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>4.1.1</version>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
